# Generated by Django 5.0.14 on 2026-07-16 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('bssid', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('ssid', models.CharField(blank=True, max_length=64)),
                ('vendor_oui', models.CharField(blank=True, max_length=8)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_scan_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_hex', models.CharField(max_length=64)),
                ('tech_list', models.JSONField(blank=True, default=list)),
                ('ndef_available', models.BooleanField(default=False)),
                ('ndef_records', models.JSONField(blank=True, default=list)),
                ('observed_at', models.DateTimeField()),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation', models.CharField(choices=[('GPS', 'GPS'), ('GLONASS', 'GLONASS'), ('GALILEO', 'Galileo'), ('BEIDOU', 'BeiDou'), ('QZSS', 'QZSS'), ('SBAS', 'SBAS'), ('IRNSS', 'IRNSS')], max_length=10)),
                ('svid', models.IntegerField()),
                ('cn0_db_hz', models.FloatField()),
                ('elevation_degrees', models.FloatField(blank=True, null=True)),
                ('azimuth_degrees', models.FloatField(blank=True, null=True)),
                ('used_in_fix', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField()),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['scan_session'], name='scans_satel_scan_se_83c402_idx')],
            },
        ),
        migrations.CreateModel(
            name='CellObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(blank=True, max_length=3)),
                ('mnc', models.CharField(blank=True, max_length=3)),
                ('carrier_name', models.CharField(blank=True, max_length=64)),
                ('radio_type', models.CharField(choices=[('GSM', 'GSM'), ('CDMA', 'CDMA'), ('UMTS', 'UMTS'), ('LTE', 'LTE'), ('NR', '5G NR')], max_length=8)),
                ('cell_id', models.CharField(blank=True, max_length=32)),
                ('tac_or_lac', models.CharField(blank=True, max_length=32)),
                ('band', models.CharField(blank=True, max_length=16)),
                ('is_serving_cell', models.BooleanField(default=False)),
                ('signal_dbm', models.IntegerField(blank=True, null=True)),
                ('rsrp', models.IntegerField(blank=True, null=True)),
                ('rsrq', models.IntegerField(blank=True, null=True)),
                ('sinr', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['scan_session', 'observed_at'], name='scans_cello_scan_se_3e0457_idx')],
            },
        ),
        migrations.CreateModel(
            name='BLEObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ble_mac', models.CharField(blank=True, max_length=17)),
                ('stable_identifier', models.CharField(blank=True, max_length=64)),
                ('rssi', models.IntegerField()),
                ('tx_power', models.IntegerField(blank=True, null=True)),
                ('manufacturer_data_raw', models.CharField(blank=True, max_length=255)),
                ('service_uuids', models.JSONField(blank=True, default=list)),
                ('device_type_guess', models.CharField(choices=[('AIRTAG', 'AirTag'), ('TILE', 'Tile'), ('SMARTTAG', 'Samsung SmartTag'), ('CHIPOLO', 'Chipolo'), ('HEADPHONES', 'Headphones'), ('WEARABLE', 'Wearable'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=12)),
                ('observed_at', models.DateTimeField()),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ble_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['scan_session', 'observed_at'], name='scans_bleob_scan_se_f81e1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WiFiObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField()),
                ('frequency_mhz', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('band', models.CharField(choices=[('2.4GHz', '2.4 GHz'), ('5GHz', '5 GHz'), ('6GHz', '6 GHz')], max_length=10)),
                ('security_type', models.CharField(choices=[('OPEN', 'Open'), ('WEP', 'WEP'), ('WPA', 'WPA'), ('WPA2', 'WPA2'), ('WPA3', 'WPA3'), ('WPA2_WPA3', 'WPA2/WPA3'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                ('capabilities_raw', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField()),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scans.accesspoint')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['access_point', 'observed_at'], name='scans_wifio_access__27c02b_idx'), models.Index(fields=['scan_session', 'access_point'], name='scans_wifio_scan_se_43b3d1_idx')],
            },
        ),
    ]
