# Generated by Django 5.0.14 on 2026-07-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='location_accuracy_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='location_provider',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='LANObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('vendor_oui', models.CharField(blank=True, max_length=8)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('observed_at', models.DateTimeField()),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.DeleteModel(
            name='NFCObservation',
        ),
        migrations.AddIndex(
            model_name='lanobservation',
            index=models.Index(fields=['scan_session', 'observed_at'], name='scans_lanob_scan_se_953dff_idx'),
        ),
    ]
