# Generated by Django 5.0.14 on 2026-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scansession_location_accuracy_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleobservation',
            name='device_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bleobservation',
            name='is_connectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bleobservation',
            name='primary_phy',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='cellobservation',
            name='arfcn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellobservation',
            name='bandwidth_khz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellobservation',
            name='physical_cell_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellobservation',
            name='timing_advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lanobservation',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lanobservation',
            name='device_type_guess',
            field=models.CharField(choices=[('ROUTER', 'Router/Gateway'), ('PRINTER', 'Printer'), ('NAS', 'NAS/File server'), ('MEDIA', 'Media/streaming device'), ('CAMERA', 'Camera'), ('WINDOWS_HOST', 'Windows host'), ('LINUX_HOST', 'Linux/Unix host'), ('IOT', 'IoT device'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='lanobservation',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteobservation',
            name='carrier_frequency_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteobservation',
            name='has_almanac_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satelliteobservation',
            name='has_ephemeris_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='center_freq0_mhz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='center_freq1_mhz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='channel_width_mhz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='is_80211mc_responder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='operator_friendly_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wifiobservation',
            name='wifi_standard',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
