# Generated by Django 5.0.14 on 2026-07-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_bleobservation_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellTower',
            fields=[
                ('tower_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mcc', models.CharField(blank=True, max_length=3)),
                ('mnc', models.CharField(blank=True, max_length=3)),
                ('tac_or_lac', models.CharField(blank=True, max_length=32)),
                ('cell_id', models.CharField(blank=True, max_length=32)),
                ('carrier_name', models.CharField(blank=True, max_length=64)),
                ('radio_type', models.CharField(blank=True, max_length=8)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='scansession',
            name='fused_accuracy_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='fused_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='fused_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellobservation',
            name='cell_tower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scans.celltower'),
        ),
    ]
