# Generated by Django 5.0.14 on 2026-07-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_backfill_cell_towers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LANDevice',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('vendor_oui', models.CharField(blank=True, max_length=8)),
                ('device_type_guess', models.CharField(choices=[('ROUTER', 'Router/Gateway'), ('PRINTER', 'Printer'), ('NAS', 'NAS/File server'), ('MEDIA', 'Media/streaming device'), ('CAMERA', 'Camera'), ('WINDOWS_HOST', 'Windows host'), ('LINUX_HOST', 'Linux/Unix host'), ('IOT', 'IoT device'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='lanobservation',
            name='lan_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scans.landevice'),
        ),
    ]
