# Generated by Django 5.0.14 on 2026-07-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_backfill_lan_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_rounded', models.FloatField()),
                ('lng_rounded', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='geocodedlocation',
            constraint=models.UniqueConstraint(fields=('lat_rounded', 'lng_rounded'), name='unique_geocoded_location'),
        ),
    ]
