# Generated by Django 5.0.14 on 2026-07-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_geocodedlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLEDevice',
            fields=[
                ('device_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=64)),
                ('device_type_guess', models.CharField(choices=[('AIRTAG', 'AirTag'), ('TILE', 'Tile'), ('SMARTTAG', 'Samsung SmartTag'), ('CHIPOLO', 'Chipolo'), ('HEADPHONES', 'Headphones'), ('WEARABLE', 'Wearable'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=12)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='bleobservation',
            name='ble_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scans.bledevice'),
        ),
    ]
