# Generated by Django 5.0.14 on 2026-08-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_wifiobservation_security_type_owe'),
        ('sensors', '0004_sensorscanpolicy_adaptive_scan_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to='sensors.sensor'),
        ),
    ]
