# Generated by Django 5.0.14 on 2026-07-16 22:06

import distribution.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_code', models.PositiveIntegerField(unique=True)),
                ('version_name', models.CharField(max_length=32)),
                ('apk_file', models.FileField(upload_to=distribution.models.apk_upload_path)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
