# Generated by Django 5.0.14 on 2026-07-17 19:59

import distribution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='build_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='build_log_tail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='build_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='build_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('BUILDING', 'Building'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='apk_file',
            field=models.FileField(blank=True, upload_to=distribution.models.apk_upload_path),
        ),
    ]
