# Generated by Django 5.0.14 on 2026-07-16 22:34

import sensors.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('android', 'Android'), ('kali_linux', 'Kali Linux (reserved for v-next)'), ('other', 'Other')], default='android', max_length=20)),
                ('token', models.CharField(default=sensors.models.generate_sensor_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
