# Generated by Django 5.0.14 on 2026-07-26 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_scan_upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SensorScanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_scan_enabled', models.BooleanField(default=False)),
                ('scan_interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)])),
                ('heartbeat_interval_seconds', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5)])),
                ('include_wifi', models.BooleanField(default=True)),
                ('include_cellular', models.BooleanField(default=True)),
                ('include_ble', models.BooleanField(default=True)),
                ('include_gnss', models.BooleanField(default=True)),
                ('scan_now_nonce', models.PositiveIntegerField(default=0)),
                ('policy_revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('reported_is_continuous', models.BooleanField(blank=True, null=True)),
                ('reported_is_scanning', models.BooleanField(blank=True, null=True)),
                ('reported_phase', models.CharField(blank=True, max_length=32)),
                ('reported_completed_scans', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_wifi_unavailable_reason', models.CharField(blank=True, max_length=200)),
                ('reported_cellular_unavailable_reason', models.CharField(blank=True, max_length=200)),
                ('reported_ble_unavailable_reason', models.CharField(blank=True, max_length=200)),
                ('reported_permissions_granted', models.BooleanField(blank=True, null=True)),
                ('reported_location_services_enabled', models.BooleanField(blank=True, null=True)),
                ('reported_pending_uploads', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_outbox_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reported_outbox_quota_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_battery_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_app_version', models.CharField(blank=True, max_length=32)),
                ('reported_policy_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_scan_now_nonce', models.PositiveIntegerField(blank=True, null=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_policy', to='sensors.sensor')),
            ],
            options={
                'verbose_name_plural': 'sensor scan policies',
            },
        ),
    ]
