# Generated by Django 5.0.14 on 2026-07-27 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_last_scan_upload_at_sensorscanpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='reported_reset_counters_nonce',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='reset_counters_nonce',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorscanpolicy',
            name='heartbeat_interval_seconds',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
