# Generated by Django 5.0.14 on 2026-08-01 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensorscanpolicy_reported_reset_counters_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='adaptive_scan_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='driving_interval_seconds',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='reported_effective_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='reported_motion_state',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='stationary_interval_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='sensorscanpolicy',
            name='walking_interval_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
