# Generated by Django 5.0.14 on 2026-08-03 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensorscanpolicy_adaptive_scan_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('device_model', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('stack_trace', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crash_reports', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
